### ISSUE TITLE
Globs in file-specs don't understand **

### ISSUE THREAD

**Issue by Dreamacro** [Khan/genqlient#167]
**Describe the bug**
When glob matching with the root directory, `go generate ./...` fails

output
```
$ go generate ./...
no queries found, looked in: **/*.graphql (configure this in genqlient.yaml)
exit status 1
```

**To Reproduce**

```yaml
schema: ../../graphql/schema.graphql

operations:
  - './**/*.graphql'

generated: ./repo/pkg/generated.go

package: pkg
```

workaround (success)
```yaml
schema: ../../graphql/schema.graphql

operations:
  - './repo/**/*.graphql'
  - './route/**/*.graphql'

generated: ./repo/pkg/generated.go

package: pkg
```

**genqlient version**
main branch
