### ISSUE TITLE
using `use_struct_references`does throws an error during at build

### ISSUE THREAD

**Issue by chronark** [Khan/genqlient#168]
**Describe the bug**
I want to use the config `use_struct_references: true` in `genqlient.yaml`but it throws an error saying it's not found in `generate.Config`
**To Reproduce**
Using this config file:
```yaml
schema: ./gql/schema.graphql
operations:
- ./gql/operations.graphql
generated: repository/gql/generated.go
use_struct_references: true
bindings:
  Time:
    type: time.Time
  Long:
    type: int64

```

Run
```
go get -d github.com/Khan/genqlient 
go run github.com/Khan/genqlient  

```

Results in
```
invalid config file genqlient.yaml: yaml: unmarshal errors:
  line 5: field use_struct_references not found in type generate.Config
exit status 1
```

**Expected behavior**
I expect it to build.

**genqlient version**
`github.com/Khan/genqlient v0.3.0`
