### ISSUE TITLE
Add support for AWS Directives and Types

### ISSUE THREAD

**Issue by treddy73** [Khan/genqlient#204]
**Is your feature request related to a problem? Please describe.**
I am unable to parse a schema that contains AWS-specific directives and types (i.e., @aws_iam, @aws_api_key, AWSTimestamp, etc.)

**Describe the solution you'd like**
Other graphql code generators for other languages are able to parse and generate code for schemas containing AWS directives

**Describe alternatives you've considered**
I've tried to remove the directives all-together when generating the code, but I continue to run into this issue #175.  The error message I see is `invalid schema: Undefined type Boolean`.  If I remove everything related to AWS, the code generator runs fine.

**Comment by benjaminjkraft** [comment]
Thanks for the report; it sounds like #175 is indeed hiding the real error.  Could you post your schema or a part of it that reproduces the issue? My guess is this may be the same problem as #200 but it's hard to tell for sure.

**Comment by benjaminjkraft** [comment]
Ok, if it's easier you can now also checkout #205 and it should give you a better error, which you can then post here.

**Comment by theAndrewCline** [comment]
@benjaminjkraft working with @treddy73 on this, 

I think we might just be adding the AWS Scalar types incorrectly. Here is a minimal repoduction.

https://github.com/theAndrewCline/go-graphql-test

**Comment by treddy73** [comment]
Thanks for pointing out #200.  I reran the schema export from AWS AppSync with the `--no-include-directives` flag and it excluded all of the AWS-specific directives.  I'm not sure how that affects code generation, but for now we're past that problem.

With the branch you provided, the error message is now: `invalid schema: Undefined type AWSTimestamp`

However, I do have a string binding (just for testing purposes) in my yaml
```
schema: schema.graphql
operations:
- genqlient.graphql
generated: internal/prpgql/generated.go
package: prpgql
use_struct_references: true
bindings:
  AWSTimestamp:
    type: string
  AWSDateTime:
    type: string
  AWSJSON:
    type: string
```

I feel like there's something else that is going on
