### ISSUE TITLE
Add request and response cases for `Optional` values

### ISSUE THREAD

**Issue by Jictyvoo** [Khan/genqlient#242]
**Is your feature request related to a problem? Please describe.**
Currently I'm using the Go default values for a response in a lot of fields. But currently I need to to send a **pointer** for optional values, and still receive the **value** as the response.

**Describe the solution you'd like**
On the file `genqlient.yaml` have a new config that receives the option that will be used on optional on request, and another option on response.

**Describe alternatives you've considered**
On the genqlient.yaml have the following alternatives:
```yaml
optional:
    request: pointer
    response: value # use value as default if empty
```

Alternative
```yaml
request:
    optional: pointer
    use_struct_references: true
response:
    optional: value
    use_struct_references: false
```
