### ISSUE TITLE
Binding to a type in the same package as generated code produces invalid output

### ISSUE THREAD

**Issue by mathewbyrne** [Khan/genqlient#283]
**Describe the bug**
Binding to a type in the same package as the generated file is not detected and results in an import loop as the package is import itself.

**To Reproduce**
Output the generated file in the same location as a bound type.
```yaml
generated: db/generated.go
bindings:
  FilterType:
    type: github.com/mathewbyrne/project/db.Filter
```

**Expected behavior**
The generated output should not have any import statement, as the type is in the same package. The type should be used directly without reference to it's package.

**genqlient version**
0.6

**Additional context**
Working around this is fairly simple by placing the generated output in a sub-package, but this still seems like a bug that could be resolved.
