### ISSUE TITLE
The Generated GraphQl query with mutation throws error for LINEAR GraphQL Query endpoint

### ISSUE THREAD

**Issue by ParthaI** [Khan/genqlient#345]
Dear team,

I've generated the queries for our project using `genqlient`. Below is the schema of the GraphQL query I'm working with:  
[GraphQL Schema](https://studio.apollographql.com/public/Linear-API/variant/current/schema/sdl?selectedSchema=%23%40%21api%21%40%23)

Here is my `genqlient.yaml` configuration:

```yaml
# Default genqlient config; for full documentation see:
# https://github.com/Khan/genqlient/blob/main/docs/genqlient.yaml
schema: schema.graphql
operations:
  - genqlient.graphql
generated: generated.go

package: gql
bindings:
  JSONObject:
    type: encoding/json.RawMessage
  JSON:
    type: encoding/json.RawMessage
  DateTime:
    type: time.Time
  TimelessDate:
    type: time.Time
  DateTimeOrDuration:
    type: time.Time
  TimelessDateOrDuration:
    type: time.Time
```

This configuration generates a function named `listIssues`. However, when I execute this function, I encounter the following error: 

`parsing time "2023-06-16" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"`.

Interestingly, the other functions seem to work fine.

Do you have any insights into why this error might be occurring?

For reference, when I run the standalone GraphQL query code, it returns the expected result:

```go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

const endpoint = "https://api.linear.app/graphql"
const apiKey = "your_api_key" // Replace with your actual API key

// GraphQL request structure
type GraphQLRequest struct {
	Query string `json:"query"`
}

// GraphQL response structure
type GraphQLResponse struct {
	Data struct {
		Issues struct {
			Nodes []struct {
				BranchName  string `json:"branchName"`
				Description string `json:"description"`
				ID          string `json:"id"`
				CreatedAt   string `json:"createdAt"`
			} `json:"nodes"`
		} `json:"issues"`
	} `json:"data"`
}

func main() {
	// Define the GraphQL query
	query := `query ExampleQuery {
		issues {
			nodes {
				branchName
				description
				id
				createdAt
			}
		}
	}`
	fmt.Println(query)

	// Prepare the GraphQL request payload
	requestBody := GraphQLRequest{
		Query: query,
	}
	jsonData, err := json.Marshal(requestBody)
	if err != nil {
		fmt.Println("Error marshalling request body:", err)
		return
	}

	// Create a new HTTP request
	req, err := http.NewRequest("POST", endpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		fmt.Println("Error creating HTTP request:", err)
		return
	}

	// Set necessary headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("%s", apiKey))

	// Send the request using http.Client
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("Error sending request:", err)
		return
	}
	defer resp.Body.Close()

	// Read and parse the response body
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("Error reading response body:", err)
		return
	}

	// Parse the JSON response into GraphQLResponse struct
	var graphQLResp GraphQLResponse
	err = json.Unmarshal(body, &graphQLResp)
	if err != nil {
		fmt.Println("Error unmarshalling response body:", err)
		return
	}

	// Print the parsed response
	for _, node := range graphQLResp.Data.Issues.Nodes {
		fmt.Printf("ID: %s\nBranch: %s\nDescription: %s\nCreated At: %s\n\n",
			node.ID, node.BranchName, node.Description, node.CreatedAt)
	}
}
```

Could you please suggest what might be going wrong? Any early suggestions would be highly appreciated.

---

### Possible Issue Explanation:
The error `parsing time "2023-06-16" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"` suggests that the date format returned by the API does not include a time component, which is expected by the default `time.Time` parsing format in Go.

### Potential Fixes:
1. **Custom Date Parsing:**
   If your API is returning dates without a time component, you may need to use a custom date type that can handle just the date, or adjust the schema binding in `genqlient.yaml` to correctly parse these dates.

2. **Adjust `genqlient.yaml` Configuration:**
   Update the `genqlient.yaml` configuration to use a custom date type that matches the API's date format. You might need to define your own custom type to handle the date parsing according to the format provided by the API.

Thanks!
